[package]
name = "steply-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
globset = "0.4.18"
indexmap = { version = "2.13.0", features = ["serde"] }
serde_json = "1.0.149"
similar = { version = "2.7.0", features = ["inline"] }
unicode-width = "0.2"
